1020 improve release process with more automations (#1021)
* remove milestone dependency

* add close section and change default branch

* Only use workflow_dispatch and add milestone mgmt

* dont include source code. Release has that by default

diff --git a/.github/workflows/CreateReleaseDraft.yml b/.github/workflows/CreateReleaseDraft.yml
--- a/.github/workflows/CreateReleaseDraft.yml
+++ b/.github/workflows/CreateReleaseDraft.yml
@@ -2,9 +2,11 @@ name: Release
 
 on:
   workflow_dispatch:
-  milestone:
-    types:
-      - closed
+    inputs:
+      CONFIRM_RELEASE:
+        description: '⚠️ The production branch will create a release draft, close the milestone, and comment on issues. Confirmation for production is required.'
+        default: false
+        type: boolean
 
 jobs:
   artifact:
@@ -21,6 +23,7 @@ jobs:
       - artifact
       - test
     runs-on: ubuntu-latest
+    if: ${{ github.event.inputs.CONFIRM_RELEASE == 'true' || github.ref != 'refs/heads/production' }}
     permissions:
       contents: write
       issues: write
@@ -30,12 +33,6 @@ jobs:
       - name: download-artifact
         id: download-artifact-release
         uses: actions/download-artifact@v4
-
-      - name: zip-artifact
-        shell: pwsh
-        run: |
-          $artifactPath = Get-ChildItem -Path "${{ steps.download-artifact-release.outputs.download-path }}" | Select-Object -First 1
-          Compress-Archive -Path "$($artifactPath.FullName)/*" -DestinationPath "${{ github.workspace }}/PSAppDeployToolKitExtensions-${{ needs.artifact.outputs.ARTIFACT_VERSION }}.zip"
 
       - name: checkout-release-manager-config
         uses: actions/checkout@v4
@@ -54,7 +51,53 @@ jobs:
         shell: pwsh
         run: dotnet tool install --global GitReleaseManager.Tool
 
-      - name: create-release
+      - name: zip-components
+        shell: pwsh
+        run: |
+          New-Item -Path "${{ github.workspace }}/components" -ItemType Directory -Force | Out-Null
+          $root = Get-ChildItem -Path "${{ steps.download-artifact-release.outputs.download-path }}" | Select-Object -First 1
+          Get-ChildItem -Path $root.FullName -Exclude 'ExtensionsSourceCode' | ForEach-Object {
+            Compress-Archive -Path $_.FullName -DestinationPath "${{ github.workspace }}/components/$($_.Name).zip"
+          }
+
+      - name: update-milestones
+        if: ${{ github.ref_name == 'production' }}
+        uses: actions/github-script@v7
+        with:
+          github-token: ${{ secrets.GITHUB_TOKEN }}
+          script: |
+            const { data: milestones } = await github.rest.issues.listMilestones({
+              owner: context.repo.owner,
+              repo: context.repo.repo,
+              state: 'open'
+            });
+
+            // Update the milestone for the current release. Note: The description will be part of the release notes.
+            const milestone = milestones.find(m => m.title === 'Next');
+            const isoDate = new Date().toISOString();
+            if (milestone) {
+              await github.rest.issues.updateMilestone({
+                owner: context.repo.owner,
+                repo: context.repo.repo,
+                milestone_number: milestone.number,
+                title: '${{ needs.artifact.outputs.ARTIFACT_VERSION }}',
+                description: 'Release version ${{ needs.artifact.outputs.ARTIFACT_VERSION }} built from commit [${{ github.sha }}](${{ github.server_url}}/${{ github.repository }}/commit/${{ github.sha }})',
+                due_on: isoDate
+              });
+            }
+            else {
+              throw new Error('Milestone not found');
+            }
+
+            // Create a new milestone for the next release
+            await github.rest.issues.createMilestone({
+              owner: context.repo.owner,
+              repo: context.repo.repo,
+              title: 'Next',
+              description: 'The next release',
+            });
+
+      - name: create-release-draft
         shell: pwsh
         run: |
           $params = @(
@@ -64,12 +107,13 @@ jobs:
             '--token', '${{ secrets.GITHUB_TOKEN }}',
             '--targetcommitish', '${{ github.sha }}',
             '--targetDirectory', '${{ github.workspace }}/ghrm/.github/GithubReleaseManager',
-            '--assets', '${{ github.workspace }}/PSAppDeployToolKitExtensions-${{ needs.artifact.outputs.ARTIFACT_VERSION }}.zip'
+            '--assets', "$((Get-ChildItem -Path "${{ github.workspace }}/components").FullName -join ',')"
           )
 
-          if ('${{ github.event_name }}' -eq 'milestone') {
-            Write-Host "Creating release from milestone '${{ github.event.milestone.title }}' on '$(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')'."
-            $params += '--milestone', '"${{ github.event.milestone.title }}"'
+          if ('${{ github.ref_name }}' -eq 'production') {
+            Write-Host "Creating production release draft."
+            # The milestone description will be part of the release notes.
+            $params += '--milestone', '${{ needs.artifact.outputs.ARTIFACT_VERSION }}'
             $params += '--name', '${{ needs.artifact.outputs.ARTIFACT_VERSION }}'
           }
           else {
@@ -83,6 +127,22 @@ jobs:
             $params += '--inputFilePath', '${{ github.workspace }}/prerelease.md'
             $params += '--name', '${{ needs.artifact.outputs.ARTIFACT_VERSION }}-${{ github.ref_name }}-unstable'
           }
+
+          $proc = Start-Process -FilePath dotnet-gitreleasemanager -ArgumentList $params -NoNewWindow -Wait -PassThru
+          exit $proc.ExitCode
+
+      - name: comment-on-issues
+        if: ${{ github.ref_name == 'production' }}
+        shell: pwsh
+        run: |
+          $params = @(
+            'close',
+            '--owner', '${{ github.repository_owner }}',
+            '--repository', '${{ github.event.repository.name }}',
+            '--token', '${{ secrets.GITHUB_TOKEN }}',
+            '--milestone', '${{ needs.artifact.outputs.ARTIFACT_VERSION }}'
+            '--targetDirectory', '${{ github.workspace }}/ghrm/.github/GithubReleaseManager'
+          )
 
           $proc = Start-Process -FilePath dotnet-gitreleasemanager -ArgumentList $params -NoNewWindow -Wait -PassThru
           exit $proc.ExitCode
